#!/usr/bin/env bash
# Generate a hardened .env for the Karaxys production/self-host stack.
#
# Every secret below is created with a cryptographically random value so no two
# installs ever share credentials. Re-running is safe: an existing .env is never
# overwritten unless you pass --force.
#
#   ./scripts/generate-secrets.sh [--env-file PATH] [--force]
set -euo pipefail

ENV_FILE="compose/prod/.env"
FORCE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --force)    FORCE=1; shift ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

command -v openssl >/dev/null 2>&1 || {
  echo "error: openssl is required to generate secrets" >&2; exit 1; }

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "refusing to overwrite existing $ENV_FILE (pass --force to replace)" >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"

# 32 random bytes, base64 — required to decode to exactly 32 bytes by the backend.
secret_key_b64="$(openssl rand -base64 32)"
api_key="$(openssl rand -hex 24)"
agent_token="$(openssl rand -hex 24)"
mongo_pass="$(openssl rand -hex 24)"
minio_pass="$(openssl rand -hex 24)"
redis_pass="$(openssl rand -hex 24)"
grafana_pass="$(openssl rand -hex 16)"
admin_pass="$(openssl rand -base64 18 | tr -d '/+=' )Aa1!"

umask 077
cat > "$ENV_FILE" <<EOF
# ─────────────────────────────────────────────────────────────────────────────
# Karaxys environment — generated by scripts/generate-secrets.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# KEEP THIS FILE SECRET. It is git-ignored. Do not commit it or paste it anywhere.
# ─────────────────────────────────────────────────────────────────────────────

COMPOSE_PROJECT_NAME=karaxys

# ── Deployment mode ──────────────────────────────────────────────────────────
#   development = local / LAN evaluation on localhost (secrets are STILL enforced)
#   production  = extra-strict startup validation; REQUIRES real non-localhost
#                 URLs + a TLS reverse proxy in front of api-server and dashboard.
KARAXYS_ENV=development

# ── Published images (flip the GHCR packages to Public, or 'docker login ghcr.io') ─
KARAXYS_IMAGE_REGISTRY=ghcr.io/karaxys
KARAXYS_IMAGE_TAG=latest

# ── Public URLs — EDIT for anything other than a single-box localhost run ────
# Browser-visible API URL (the dashboard calls this from the user's browser).
KARAXYS_PUBLIC_API_BASE_URL=http://localhost:8081
KARAXYS_API_BASE_URL=http://localhost:8081
# CORS allow-list. In production mode this must NOT be localhost or '*'.
KARAXYS_ALLOWED_ORIGINS=http://localhost:7000

# ── Generated secrets — unique to this install ───────────────────────────────
KARAXYS_SECRET_KEY_B64=$secret_key_b64
KARAXYS_API_KEY=$api_key
KARAXYS_AGENT_TOKEN=$agent_token

MONGO_ROOT_USERNAME=karaxys
MONGO_ROOT_PASSWORD=$mongo_pass
MONGO_DB_NAME=karaxys

MINIO_ROOT_USER=karaxys
MINIO_ROOT_PASSWORD=$minio_pass
KARAXYS_OBJECTSTORE_BUCKET=karaxys

KARAXYS_REDIS_PASSWORD=$redis_pass

# ── First-run admin account (created once by the admin-seed service) ─────────
KARAXYS_ADMIN_EMAIL=admin@karaxys.local
KARAXYS_ADMIN_PASSWORD=$admin_pass
KARAXYS_ADMIN_NAME=Karaxys Admin

# ── Monitoring profile (optional) ────────────────────────────────────────────
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafana_pass
EOF

echo "Wrote $ENV_FILE with freshly generated secrets."
echo
echo "  Admin login:  admin@karaxys.local"
echo "  Admin passw:  $admin_pass"
echo
echo "Save the admin password now, then start the stack with:  make prod-up"
